name: Submit a paper presentation
description: Propose a weekend to present a paper
title: "[Presentation] <yyyy-mm-dd> <username> - <short title>"
labels: ["presentation"]
body:
  - type: input
    id: date
    attributes:
      label: Weekend date (yyyy-mm-dd)
      description: Must be Saturday or Sunday
      placeholder: 2025-11-22
    validations:
      required: true
  - type: input
    id: presenter_username
    attributes:
      label: Username (profile key)
      placeholder: adnane
    validations:
      required: true
  - type: input
    id: presenter_first
    attributes:
      label: First name
    validations:
      required: true
  - type: input
    id: presenter_last
    attributes:
      label: Last name
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Paper title
    validations:
      required: true
  - type: input
    id: paper_url
    attributes:
      label: Paper URL (arXiv, PDF, etc.)
      placeholder: https://arxiv.org/abs/xxxx.xxxxx
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Optional short description
      placeholder: One or two lines…
    validations:
      required: false
  - type: input
    id: recording_url
    attributes:
      label: Recording URL (leave empty for now)
    validations:
      required: false
